# Generated by Django 3.0.5 on 2021-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
