# Generated by Django 3.0.5 on 2021-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_blooddonate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='gender',
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
