# Generated by Django 3.0.5 on 2021-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20210727_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
