# Generated by Django 3.0.5 on 2021-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donor_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='civilid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='pcrreport',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/Donor/'),
        ),
    ]
