# Generated by Django 3.0.5 on 2021-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pcrreport',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/Patient/'),
        ),
    ]
